### ISSUE TITLE
Session Message has zero for some fields when decoding Garmin FIT files

### ISSUE THREAD

**Issue by muzoman** [FitnessKit/FitDataProtocol#4]
I've been testing the software and getting some good results! When decoding Wahoo and Zwift generated FIT files everything looks good, then I started testing Garmin FIT files and have found the following some incorrect values in the SummaryRecord:

1. AverageSpeed - always zero in 3 files - but maximum speed was correct
2. AveragePower - 10320.0 - expected 180W in one case - always an order of magnitude wrong
3. TotalWork - had various incorrect values
4. Average & Max HeartRate - both incorrect - very low values

Is there something different about the way that Garmin FIT files should be handled?

**Comment by khoogheem** [comment]
Do you have the Java Tools from the SDK to turn those into CSV Files?  it would be interesting to see what those numbers show.  I have seen some of the generated files from the C lib show numbers that were order of magnitude wrong.  

If you have some example files you can share that would help me as well to look into what might be going on.

Average Power is odd.. Since that is suppose to be scale of 1 Watt.

The test files I have used were Example files from Garmin.  Files that we created from the C Lib in a project we developed for a HR monitor and some others that I have dug up from other applications that generate files.

**Comment by muzoman** [comment]
Hi Kevin!

Here's a link to a cycling activity in Garmin Connect:
https://connect.garmin.com/modern/activity/2428379312

Here's the FIT file that Garmin generated from it:
[2428379312.zip](https://github.com/FitnessKit/FitDataProtocol/files/2721004/2428379312.zip)

In this file the Session Message is reporting (all "valid" flags are true):
AverageSpeed = 0 
AveragePower = 10320.0 
AverageHeartRate = 2.0 
MaximumHeartRate = 7.0
TotalWork = 52739.0
TotalCalories = 0

Other data fields appear correct. I'll have a play with the Java tools and see what the SDK makes of the file too.

**Comment by muzoman** [comment]
What I can't seem to find is the official documentation that defines the base data type sizes and ordering for all the fields in any given message. Is this only defined in code do you know?

**Comment by muzoman** [comment]
I had a look at SessionMesg.java and compared to SessionMessagekeys.swift and there's a discrepancy in the enum definitions towards the end. Some fields are not present in the swift but where the fields are in both, field "averageVam" has a value of 130 in swift and 139 in java. Not convinced this could lead to the problems I'm seeing though...
<img width="977" alt="screenshot 2019-01-02 at 15 43 04" src="https://user-images.githubusercontent.com/320009/50599335-b0327400-0ea5-11e9-81f5-07790bedf798.png">

**Comment by khoogheem** [comment]
Thanks... I will look at this.
Yes. Looks like VAM is incorrect, that will be fixed.  But shouldn't be causing these issues.

The Data Types, they are not in any documentation.  Based on the C libs is where I determine if things are uint8s/ vs 16, etc.  That may be what is causing some of this.
Ordering of the fields can be done in any way you want.  I just happen to put them in numerical order, the C lib doesn't have any them in any particular order.

I am sure it will turn out to be something stupid on my side ;)

**Comment by muzoman** [comment]
Hi Kevin, thanks! What is puzzling is why Zwift & Wahoo Session Messages should decode OK, but not Garmin.

**Comment by khoogheem** [comment]
Ok.. I found the issue.  Looks like I was only pulling a couple data points out of the wrong size, which threw things for a whack.  What I expect is that some of those fields are not used in the Zwift/Wahoo fit files.  This can happen when using the C Lib, where thy have a program to create a Header based only on the Fields that you want to output.  

Which is actually the way I do encodes (Saves space in the file).. So lets say totalWork is nil, that field definition doesn't get added to the FIT file, since it won't actually show up as data.

let me do some more testing today and look over a few other spots. to make sure I didn't do the same thing in the Lap message, which is very similar to Session.

**Comment by muzoman** [comment]
Kevin, that's amazing, well done! I've just trawled comparing the data types list for Session Messages between swift and C and they're all good.

**Comment by khoogheem** [comment]
It was the Total Work.  I was pulling UInt16 vs 32, so everything gets shifted and screwed up ;)

**Comment by muzoman** [comment]
I can see how that could easily happen! :-)

**Comment by muzoman** [comment]
How's it going Kevin? I noticed that the same issue is in the Lap Message too.

I was wondering if a little code change could avoid this issue - by dynamically determining the correct decode/encode function from the enumeration in SessionMessage.FitCodingKeys - the correct data types for each field are defined there - and if you looked this up and called the associated encode/decode function then you could remove the case statements that are currently used to associate decode/encode functions with fields.

**Comment by khoogheem** [comment]
Yep.. got that one fixed yesterday as well.

I have a few things planned here to clean up later.  Your suggestion is part of what I have had in mind for a while.  However I can't fully remove the case statements for the decoding.  But a more dynamic approach to the solution will some what work.

**Comment by muzoman** [comment]
Yes, agreed about not being able to fully remove the case statements.

**Comment by khoogheem** [comment]
I have pushed up 0.21.1 which addresses these issues.

Pod update is on its way
