### ISSUE TITLE
Compilation Warnings

### ISSUE THREAD

**Issue by muzoman** [FitnessKit/FitDataProtocol#5]
When compiling FitDataProtocol, quite a few files generate these warning. Not sure what they relate to Kevin:

<img width="682" alt="screenshot 2019-01-03 at 15 21 23" src="https://user-images.githubusercontent.com/320009/50645399-60b67b80-0f6b-11e9-8650-11218f37f321.png">

**Comment by khoogheem** [comment]
This is more for backward compatibility for EventTypes that are deprecated in the FIT spec.

If reading an old FIT file that used those, you can still tell what they were.  But it indicates that creating a new FIT file they should not be included anymore.

The problem is that there is no other good way to indicate this with Swift but to use the deprecated warning.

**Comment by khoogheem** [comment]
The only other option is that I remove them and remap them to something current if we decode that in a Fit File.  

For example:
- begin maps to start
- end/endAll maps to stop
- consecutive maps to ?? marker maybe

**Comment by muzoman** [comment]
I like that suggestion, but also understand if you’d prefer to keep the deprecated event detection. I guess there’s no guidance notes on the issue in the SDK release notes?

**Comment by khoogheem** [comment]
HAHA no.

The other option is to do what the Java Lib and just call the events:

- consecutiveDepreciated
- beginDepreciated

IMHO that looks like crap

**Comment by muzoman** [comment]
Agreed, I guess real life users just want their files to import as accurately as possible so your suggestion to map the legacy events to current ones makes most sense I think.
